services:
  db:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "password"
    expose:
     - "5432"
    ports:
     - "5432:5432"
    entrypoint: ["docker-entrypoint.sh", "-c", "shared_buffers=256MB", "-c", "max_connections=1000"]

  app_debug:
    build:
      context: .
      target: app_debug
    depends_on:
     - db
    ports:
      - "5030:5030"
    environment:
      ASPNETCORE_URLS: "http://*:5030"
      BoardGames__UsePostgreSql: "Server=db;Database=boardgames;Port=5432;User Id=postgres;Password=postgres"

  app_release:
    build:
      context: .
      target: app_release
    depends_on:
     - db
    ports:
     - "80:80"
    environment:
      ASPNETCORE_URLS: "http://*:80"
      HTTPS_PORT: 443
      BoardGames__UsePostgreSql: "Server=db;Database=boardgames;Port=5432;User Id=postgres;Password=postgres"
