// <auto-generated />
using System;
using BoardGames.HostServices;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BoardGames.Migrations.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20261004015113_FusionV15OperationsSchema")]
partial class _20261004015113_FusionV15OperationsSchema
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "11.0.0-rc.1.26425.128")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("ActualLab.Fusion.Authentication.Services.DbSessionInfo<long>", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<string>("AuthenticatedIdentity")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("IPAddress")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<bool>("IsSignOutForced")
                    .HasColumnType("boolean");

                b.Property<DateTime>("LastSeenAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("OptionsJson")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("UserAgent")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<long>("UserId")
                    .HasColumnType("bigint");

                b.Property<long>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("bigint");

                b.HasKey("Id");

                b.HasIndex("CreatedAt", "IsSignOutForced");

                b.HasIndex("IPAddress", "IsSignOutForced");

                b.HasIndex("LastSeenAt", "IsSignOutForced");

                b.HasIndex("UserId", "IsSignOutForced");

                b.ToTable("_Sessions");
            });

        modelBuilder.Entity("ActualLab.Fusion.Authentication.Services.DbUser<long>", b =>
            {
                var id = b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(id);

                b.Property<string>("ClaimsJson")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<long>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("bigint");

                b.HasKey("Id");

                b.HasIndex("Name");

                b.ToTable("Users");
            });

        modelBuilder.Entity("ActualLab.Fusion.Authentication.Services.DbUserIdentity<long>", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("text");

                b.Property<long>("DbUserId")
                    .HasColumnType("bigint")
                    .HasColumnName("UserId");

                b.Property<string>("Secret")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("DbUserId");

                b.HasIndex("Id");

                b.ToTable("UserIdentities");
            });

        modelBuilder.Entity("ActualLab.Fusion.EntityFramework.Operations.DbEvent", b =>
            {
                b.Property<string>("Uuid")
                    .HasColumnType("text");

                b.Property<DateTime>("DelayUntil")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("LoggedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("State")
                    .HasColumnType("integer");

                b.Property<byte[]>("ValueData")
                    .HasColumnType("bytea");

                b.Property<string>("ValueJson")
                    .HasColumnType("text");

                b.Property<long>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("bigint");

                b.HasKey("Uuid");

                b.HasIndex("DelayUntil", "State");

                b.HasIndex("State", "DelayUntil");

                b.ToTable("_Events");
            });

        modelBuilder.Entity("ActualLab.Fusion.EntityFramework.Operations.DbOperation", b =>
            {
                var index = b.Property<long>("Index")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(index);

                b.Property<byte[]>("CommandData")
                    .HasColumnType("bytea");

                b.Property<string>("CommandJson")
                    .HasColumnType("text");

                b.Property<string>("HostId")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<byte[]>("InvalidationCallsData")
                    .HasColumnType("bytea");

                b.Property<string>("InvalidationCallsJson")
                    .HasColumnType("text");

                b.Property<DateTime>("LoggedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Uuid")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Index");

                b.HasIndex("LoggedAt");

                b.HasIndex("Uuid")
                    .IsUnique();

                b.ToTable("_Operations");
            });

        modelBuilder.Entity("BoardGames.HostServices.DbChatMessage", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("text");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("DbChatId")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("ChatId");

                b.Property<long>("DbUserId")
                    .HasColumnType("bigint")
                    .HasColumnName("UserId");

                b.Property<DateTime>("EditedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<bool>("IsRemoved")
                    .HasColumnType("boolean");

                b.Property<string>("Text")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("DbChatId", "CreatedAt");

                b.HasIndex("DbChatId", "Id", "CreatedAt");

                b.HasIndex("DbUserId", "CreatedAt", "DbChatId");

                b.HasIndex("DbUserId", "DbChatId", "CreatedAt");

                b.HasIndex("DbUserId", "DbChatId", "Id", "CreatedAt");

                b.HasIndex("DbUserId", "Id", "CreatedAt", "DbChatId");

                b.ToTable("ChatMessages");
            });

        modelBuilder.Entity("BoardGames.HostServices.DbGame", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("text");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<long>("DbUserId")
                    .HasColumnType("bigint")
                    .HasColumnName("UserId");

                b.Property<DateTime?>("EndedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("EngineId")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Intro")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<bool>("IsPublic")
                    .HasColumnType("boolean");

                b.Property<DateTime?>("LastMoveAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<long?>("MaxScore")
                    .HasColumnType("bigint");

                b.Property<int?>("RoundCount")
                    .HasColumnType("integer");

                b.Property<int>("RoundIndex")
                    .HasColumnType("integer");

                b.Property<int>("Stage")
                    .HasColumnType("integer");

                b.Property<DateTime?>("StartedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("StateJson")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("StateMessage")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("DbUserId", "CreatedAt", "Stage");

                b.HasIndex("DbUserId", "Stage", "CreatedAt");

                b.HasIndex("Stage", "IsPublic", "CreatedAt");

                b.ToTable("Games");
            });

        modelBuilder.Entity("BoardGames.HostServices.DbGamePlayer", b =>
            {
                b.Property<string>("DbGameId")
                    .HasColumnType("text")
                    .HasColumnName("GameId");

                b.Property<long>("DbUserId")
                    .HasColumnType("bigint")
                    .HasColumnName("UserId");

                b.Property<string>("EngineId")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("Index")
                    .HasColumnType("integer");

                b.Property<long>("Score")
                    .HasColumnType("bigint");

                b.HasKey("DbGameId", "DbUserId");

                b.HasIndex("EngineId", "Score");

                b.ToTable("GamePlayers");
            });

        modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
            {
                var id = b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(id);

                b.Property<string>("FriendlyName")
                    .HasColumnType("text");

                b.Property<string>("Xml")
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("DataProtectionKeys");
            });

        modelBuilder.Entity("ActualLab.Fusion.Authentication.Services.DbUserIdentity<long>", b =>
            {
                b.HasOne("ActualLab.Fusion.Authentication.Services.DbUser<long>", null)
                    .WithMany("Identities")
                    .HasForeignKey("DbUserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("BoardGames.HostServices.DbGamePlayer", b =>
            {
                b.HasOne("BoardGames.HostServices.DbGame", null)
                    .WithMany("Players")
                    .HasForeignKey("DbGameId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("ActualLab.Fusion.Authentication.Services.DbUser<long>", b =>
            {
                b.Navigation("Identities");
            });

        modelBuilder.Entity("BoardGames.HostServices.DbGame", b =>
            {
                b.Navigation("Players");
            });
#pragma warning restore 612, 618
    }
}
